module.exports = {
  up: (QueryInterface) =>
    QueryInterface.bulkInsert("Products", [
      {
        id: 70709795,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/293238_2",
        name: "Borracha Escolar Faber Castell Super Soft",
        categories: "Bazar E Utilidades",
        price: 5.39,
        brand: "Faber Castell",
      },
      {
        id: 70709271,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/296943_2",
        name: "Cereal Barra Linea 60g Cookies Cream",
        categories: "Mercearia",
        price: 4.99,
        brand: "Linea",
      },
      {
        id: 70712433,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/268054_2",
        name: "Sobremesa Chandelle 200g Chantilly Caramelo",
        categories: "Laticínios",
        price: 4.99,
        brand: "Chandelle",
      },
      {
        id: 70710768,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/285909_2",
        name: "Absorvente Always Com 8 Super Protecao Com Abas Suave",
        categories: "Perfumaria E Beleza",
        price: 4.19,
        brand: "Always",
      },
      {
        id: 70707050,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/448210_2",
        name: "Tempero Smart Zero Sódio 48g Frango",
        categories: "Mercearia",
        price: 18.38,
        brand: "Smart",
      },
      {
        id: 70703001,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/305299_2",
        name: "Amaciante Roupa Baby Soft 5l Toque Cuidado",
        categories: "Limpeza",
        price: 13.95,
        brand: "Baby Soft",
      },
      {
        id: 70714252,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/270090_2",
        name: "Acendedor Alcool Solido Fiat Lux",
        categories: "Bazar E Utilidades",
        price: 11.49,
        brand: "Fiat Lux",
      },
      {
        id: 70710641,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/291388_2",
        name: "Mostarda Kuhne 255g Levemente Picante",
        categories: "Mercearia",
        price: 18.68,
        brand: "Kuhne",
      },
      {
        id: 70705194,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/276040_2",
        name: "Vagem Macarrao Organica Solo Vivo 300g",
        categories: "Hortifruti",
        price: 6.99,
        brand: "Solo Vivo",
      },
      {
        id: 70712494,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/278834_2",
        name: "Pao De Alho Zinho 300g Picante",
        categories: "Padaria",
        price: 10.89,
        brand: "Zinho",
      },
      {
        id: 70703339,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/448021_2",
        name: "Detergente Líquido Triex 500ml Clear",
        categories: "Limpeza",
        price: 1.29,
        brand: "Triex",
      },
      {
        id: 70704403,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/275288_2",
        name: "Molho Tomate Barilla 400g Olive",
        categories: "Mercearia",
        price: 21.9,
        brand: "Barilla",
      },
      {
        id: 70713537,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/289634_2",
        name: "Vinho Chileno Leon De Tarapacá 750ml Cabernet Sauvignon",
        categories: "Bebidas",
        price: 64.9,
        brand: "León Tarapacá",
      },
      {
        id: 70710468,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/288750_2",
        name: "Coxa Sobrecoxa Frango Frimesa 700g Empanado",
        categories: "Frios E Congelados",
        price: 19.9,
        brand: "Frimesa",
      },
      {
        id: 70714725,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/294551_2",
        name: "Vaso Flor De Maio P11",
        categories: "Flores E Plantas",
        price: 9.98,
        brand: "Sem Marca",
      },
      {
        id: 70705832,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/270399_2",
        name: "Chocolate Granulado Dori 215g Copo",
        categories: "Mercearia",
        price: 7.57,
        brand: "Dori",
      },
      {
        id: 70715195,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/283047_2",
        name: "Protetor Sol Sundown 120ml Fps30",
        categories: "Perfumaria E Beleza",
        price: 39.9,
        brand: "Sundown",
      },
      {
        id: 70707642,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/445130_2",
        name: "Hamburguer Sadia Speciale 175g Bovino",
        categories: "Frios E Congelados",
        price: 17.9,
        brand: "Speciale",
      },
      {
        id: 70704904,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/289908_2",
        name: "Bebida Máquina Pilão 104g Café Espresso 12",
        categories: "Mercearia",
        price: 26.6,
        brand: "Pilão",
      },
      {
        id: 70705942,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/447240_2",
        name: "Bala Gelatina Fini 90g Ice Cream",
        categories: "Mercearia",
        price: 6.99,
        brand: "Fini",
      },
      {
        id: 70705544,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/289629_2",
        name: "Vinho Chileno Concha Y Toro Reservado 750ml Sauvignon Blanc",
        categories: "Bebidas",
        price: 35.9,
        brand: "Concha Y Toro",
      },
      {
        id: 70713955,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/294283_2",
        name: "Condicionador Pantene 400ml Cachos Definid",
        categories: "Perfumaria E Beleza",
        price: 26.4,
        brand: "Pantene",
      },
      {
        id: 70709351,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/299347_2",
        name: "Cereal Mucilon 180g Sac Ameixa-Aveia",
        categories: "Mercearia",
        price: 6.99,
        brand: "Mucilon",
      },
      {
        id: 70710398,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/289321_2",
        name: "Cereal Barra Nuts Linea 50g Tradicional",
        categories: "Mercearia",
        price: 9.56,
        brand: "Linea",
      },
      {
        id: 70711199,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/281910_2",
        name: "Leite Fermentado Liquido Activia 170g Sem Lactose Ameixa",
        categories: "Laticínios",
        price: 3.29,
        brand: "Activa",
      },
      {
        id: 70709841,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/293065_2",
        name: "Geleia Saint Dalfour 284g Quatro Frutas",
        categories: "Mercearia",
        price: 36.9,
        brand: "St. Dalfour",
      },
      {
        id: 70709073,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/446805_2",
        name: "Sabonete Antibacterial Rexona 84g Limpeza Profunda",
        categories: "Perfumaria E Beleza",
        price: 1.58,
        brand: "Rexona",
      },
      {
        id: 70709547,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/445533_2",
        name: "Lápis Sobrancelha Vult 1,2g 003",
        categories: "Perfumaria E Beleza",
        price: 14.79,
        brand: "Vult",
      },
      {
        id: 70703240,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/269657_2",
        name: "Alcool Bacfree Coperalcool 500ml 46graus Tradicional",
        categories: "Limpeza",
        price: 5.58,
        brand: "Coperalcool",
      },
      {
        id: 70711969,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/273823_2",
        name: "Vodka Kislla 900ml Limao",
        categories: "Bebidas",
        price: 14.79,
        brand: "Kislla",
      },
      {
        id: 70707225,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/448648_2",
        name: "Caneca Vidro Cedar Glass 250ml Tokyo",
        categories: "Bazar E Utilidades",
        price: 8.95,
        brand: "Cedar",
      },
      {
        id: 70705825,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/444853_2",
        name: "Oleo Canola Salada 900ml Especial",
        categories: "Mercearia",
        price: 9.98,
        brand: "Salada",
      },
      {
        id: 70713283,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/449495_2",
        name: "Loção Hidratante Dove 200ml Nutri Essencial",
        categories: "Perfumaria E Beleza",
        price: 12.49,
        brand: "Dove",
      },
      {
        id: 70710844,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/290619_2",
        name: "Cachaca Salinas 700ml Umburana",
        categories: "Bebidas",
        price: 43.9,
        brand: "Salinas",
      },
      {
        id: 70707908,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/444209_2",
        name: "Iogurte Líquido Nesfit 150g Sem Lactose Morango Aveia Baunil",
        categories: "Laticínios",
        price: 2.99,
        brand: "Nesfit",
      },
      {
        id: 70715085,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/272241_2",
        name: "Churrasq Mor Montana",
        categories: "Bazar E Utilidades",
        price: 137.9,
        brand: "Mor",
      },
      {
        id: 70706640,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/449424_2",
        name: "Pao Pita Bread 300g Mini Sirio",
        categories: "Padaria",
        price: 8.19,
        brand: "Wickbold",
      },
      {
        id: 70714886,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/294824_2",
        name: "Tintura Nutrisse Aveia 60",
        categories: "Perfumaria E Beleza",
        price: 24.9,
        brand: "Nutrisse",
      },
      {
        id: 70711087,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/282561_2",
        name: "Alho Granulado Kisabor 30g",
        categories: "Mercearia",
        price: 4.48,
        brand: "Kisabor",
      },
      {
        id: 70710521,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/289942_2",
        name: "Iogurte Polpa Activia 120g Pedaços Frutas Silvestres",
        categories: "Laticínios",
        price: 3.65,
        brand: "Activa",
      },
      {
        id: 70707471,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/446156_2",
        name: "Brócolis Rama Campo Alegre 200g",
        categories: "Hortifruti",
        price: 6.5,
        brand: "Campo Alegre",
      },
      {
        id: 70708013,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/320207_2",
        name: "Pó Facial Hd Vult 9g Solto Translucido",
        categories: "Perfumaria E Beleza",
        price: 30.9,
        brand: "Vult",
      },
      {
        id: 70710647,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/291386_2",
        name: "Mini Milho Conserva Kuhne 110g",
        categories: "Mercearia",
        price: 15.39,
        brand: "Kuhne",
      },
      {
        id: 70713073,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/293823_2",
        name: "Vinho Chileno Emiliana Adobe 750ml Pinot Noir Tinto",
        categories: "Bebidas",
        price: 95.9,
        brand: "Emiliana",
      },
      {
        id: 70714714,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/286944_2",
        name: "Joelho Da Paleta Resfriado 1,200kg Bandeja",
        categories: "Carnes",
        price: 17.88,
        brand: "Sem Marca",
      },
      {
        id: 70710075,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/291509_2",
        name: "Leite Po Sem Lactose Supra Soy 300g Nature",
        categories: "Bebidas",
        price: 22.9,
        brand: "Supra Soy",
      },
      {
        id: 70703581,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/304479_2",
        name: "Biscoito Rosquinha Galo 400g Coco",
        categories: "Mercearia",
        price: 3.99,
        brand: "Galo",
      },
      {
        id: 70710202,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/291056_2",
        name: "Bolinho Suavipan 40g Zero Acucar Baunilha Com Chocolate",
        categories: "Mercearia",
        price: 3.69,
        brand: "Suavipan",
      },
      {
        id: 70705957,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/446494_2",
        name: "Salgadinho Batata Pringles 112g Wavy Barbecue",
        categories: "Mercearia",
        price: 17.49,
        brand: "Pringles",
      },
      {
        id: 70714265,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/448031_2",
        name: "Creme Pentear Niely Gold 250g Liso Pleno",
        categories: "Perfumaria E Beleza",
        price: 8.39,
        brand: "Niely Gold",
      },
      {
        id: 70714498,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/265409_2",
        name: "Vela Moroaba 380g Novena",
        categories: "Bazar E Utilidades",
        price: 16.55,
        brand: "Moroaba",
      },
      {
        id: 70710885,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/284377_2",
        name: "Cerveja Martina Witbier 600ml",
        categories: "Bebidas",
        price: 13.29,
        brand: "Martina",
      },
      {
        id: 70713414,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/284786_2",
        name: "Sabonete Liquid Anti Bacteriano Maos Protex 250ml Vitamina E",
        categories: "Perfumaria E Beleza",
        price: 11.98,
        brand: "Protex",
      },
      {
        id: 70706699,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/275541_2",
        name: "Cookie Jasmine 150g Integ Limao",
        categories: "Mercearia",
        price: 6.99,
        brand: "Jasmine",
      },
      {
        id: 70715255,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/273300_2",
        name: "Locao Hidrat Paixao 200ml Paixao Irresist",
        categories: "Perfumaria E Beleza",
        price: 9.95,
        brand: "Paixão",
      },
      {
        id: 70704503,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/264263_2",
        name: "Salada 02 Horticultura Felicio 180g",
        categories: "Hortifruti",
        price: 4.5,
        brand: "Hf",
      },
      {
        id: 70707846,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/444384_2",
        name: "Sorvete Jundia 2l Flocos",
        categories: "Laticínios",
        price: 19.98,
        brand: "Jundiá",
      },
      {
        id: 70712370,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/273028_2",
        name: "Brinquedo Nerf N-Strike Elite Firestrike",
        categories: "Bazar E Utilidades",
        price: 133.9,
        brand: "Elite",
      },
      {
        id: 70712301,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/280323_2",
        name: "Macarrao De Cecco 500g Rigatoni N24",
        categories: "Mercearia",
        price: 12.9,
        brand: "De Cecco",
      },
      {
        id: 70712434,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/272808_2",
        name: "Sobremesa Chandelle 360gr Chocolate Branco",
        categories: "Laticínios",
        price: 5.99,
        brand: "Chandelle",
      },
      {
        id: 70704939,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/287892_2",
        name: "Gergelim Mae Terra 200g Integral",
        categories: "Mercearia",
        price: 6.99,
        brand: "Mãe Terra",
      },
      {
        id: 70711774,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/295014_2",
        name: "Esmalte Colorama Crem Black",
        categories: "Perfumaria E Beleza",
        price: 6.39,
        brand: "Colorama",
      },
      {
        id: 70707047,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/448203_2",
        name: "Sorvete Ski Cream 400ml Napolitano",
        categories: "Laticínios",
        price: 7.9,
        brand: "Skimoni",
      },
      {
        id: 70703757,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/288740_2",
        name: "Cerveja Itaipava 350ml Lata Malzebier",
        categories: "Bebidas",
        price: 3.29,
        brand: "Itaipava",
      },
      {
        id: 70703638,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/296919_2",
        name: "Biscoito Wafer Garoto 110g Chocolate",
        categories: "Mercearia",
        price: 1.59,
        brand: "Garoto",
      },
      {
        id: 70711931,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/270642_2",
        name: "Caldo Po Kitano 37,5g Carne",
        categories: "Mercearia",
        price: 1.29,
        brand: "Kitano",
      },
      {
        id: 70705229,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/274315_2",
        name: "Hamburguer Angus Seara 400g Gourmet",
        categories: "Frios E Congelados",
        price: 21.39,
        brand: "Seara",
      },
      {
        id: 70704996,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/283007_2",
        name: "Cafe Do Ponto 250g Safra Especial",
        categories: "Mercearia",
        price: 9.19,
        brand: "Do Ponto",
      },
      {
        id: 70704257,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/290236_2",
        name: "Sabonete Francis Classico 90g Azul",
        categories: "Perfumaria E Beleza",
        price: 2.89,
        brand: "Francis",
      },
      {
        id: 70709406,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/449181_2",
        name: "Salgadinho Batata Ruffles 50g Onda Mais Queijo",
        categories: "Mercearia",
        price: 4.59,
        brand: "Elma Chips",
      },
      {
        id: 70708048,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/308681_2",
        name: "Máscara Facial Garnier Hidra Bomb Camomila",
        categories: "Perfumaria E Beleza",
        price: 18.5,
        brand: "Garnier",
      },
      {
        id: 70706707,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/290936_2",
        name: "Contra File Bovino 4,500kg Peca Vacuo",
        categories: "Carnes",
        price: 36.9,
        brand: "Friboi",
      },
      {
        id: 70714427,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/276897_2",
        name: "Resistencia Para Chuv Lorenzetti 220v",
        categories: "Bazar E Utilidades",
        price: 5.98,
        brand: "Lorenzetti",
      },
      {
        id: 70714035,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/265889_2",
        name: "Pe Moleque Falex 130g Crocante",
        categories: "Mercearia",
        price: 4.79,
        brand: "Falex",
      },
      {
        id: 70707928,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/444148_2",
        name: "Biscoito Nesfit 160g Laranja E Cenoura",
        categories: "Mercearia",
        price: 2.69,
        brand: "Nesfit",
      },
      {
        id: 70715532,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/264228_2",
        name: "Lenco Papel Kleenex Com 50",
        categories: "Perfumaria E Beleza",
        price: 5.19,
        brand: "Kleenex",
      },
      {
        id: 70707321,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/448931_2",
        name: "Pizza Seara Gourmet 450g Margherita",
        categories: "Frios E Congelados",
        price: 25.78,
        brand: "Seara",
      },
      {
        id: 70709997,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/292775_2",
        name: "Vinho Português Terra Brava 750ml Tinto",
        categories: "Bebidas",
        price: 57.9,
        brand: "Terra Brava",
      },
      {
        id: 70708182,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/306186_2",
        name: "Shampoo 200ml E Condicionador Head &Sholders170ml Detox Raiz",
        categories: "Perfumaria E Beleza",
        price: 33.9,
        brand: "Head & Shoulders",
      },
      {
        id: 70708991,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/303035_2",
        name: "Prato Sobremesa Nadir Opaline Pétala",
        categories: "Bazar E Utilidades",
        price: 7.58,
        brand: "Nadir",
      },
      {
        id: 70714462,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/284779_2",
        name: "Sabonete Liquido Palmolive 250ml Nutri Milk",
        categories: "Perfumaria E Beleza",
        price: 6.99,
        brand: "Palmolive",
      },
      {
        id: 70706219,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/289999_2",
        name: "Açai Frooty 700ml Natural",
        categories: "Laticínios",
        price: 19.9,
        brand: "Frooty",
      },
      {
        id: 70708662,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/305647_2",
        name: "Sorvete Skimoni 1,5l Flocos",
        categories: "Laticínios",
        price: 19.98,
        brand: "Skimoni",
      },
      {
        id: 70708157,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/305808_2",
        name: "Complemento Alimentar Nutren 740g Senior Café Com Leite",
        categories: "Mercearia",
        price: 119.9,
        brand: "Nutren",
      },
      {
        id: 70704497,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/446874_2",
        name: "Creme Dental Close Up Liquifresh 100g Ice",
        categories: "Perfumaria E Beleza",
        price: 5.19,
        brand: "Closeup",
      },
      {
        id: 70709512,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/445557_2",
        name: "Pó Compacto Vult 9g Ilum Bronze",
        categories: "Perfumaria E Beleza",
        price: 23.49,
        brand: "Vult",
      },
      {
        id: 70714260,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/270200_2",
        name: "Sorvete Pimpinella 2l Maracuja",
        categories: "Laticínios",
        price: 21.9,
        brand: "Pimpeniella",
      },
      {
        id: 70709509,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/445560_2",
        name: "Pó Compacto Vult 9g Ilum Gold",
        categories: "Perfumaria E Beleza",
        price: 23.49,
        brand: "Vult",
      },
      {
        id: 70714319,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/283670_2",
        name: "Apararelho Barbear Prestobarba 3 C/2 Feminino",
        categories: "Perfumaria E Beleza",
        price: 15.9,
        brand: "Prestobarba",
      },
      {
        id: 70703323,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/281253_2",
        name: "Guard Pap Snob Gala F.D Gde",
        categories: "Bazar E Utilidades",
        price: 8.75,
        brand: "Snob",
      },
      {
        id: 70709365,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/447455_2",
        name: "Sabonete Antibacteriano Protex 125g Limpeza Profunda Orig",
        categories: "Perfumaria E Beleza",
        price: 3.29,
        brand: "Protex",
      },
      {
        id: 70711349,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/280435_2",
        name: "Farofa Pronta Angelica 250g Picante",
        categories: "Mercearia",
        price: 3.29,
        brand: "Angelica",
      },
      {
        id: 70710419,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/304079_2",
        name: "Requeijão Bandeira 200g",
        categories: "Laticínios",
        price: 6.39,
        brand: "Bandeira",
      },
      {
        id: 70711194,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/288880_2",
        name: "Oleo Eucalipto Sanol 120ml",
        categories: "Limpeza",
        price: 14.9,
        brand: "Sanol",
      },
      {
        id: 70709648,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/445370_2",
        name: "Base Líquida Vult Alta Cobertura 26ml B05",
        categories: "Perfumaria E Beleza",
        price: 38.9,
        brand: "Vult",
      },
      {
        id: 70704123,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/446775_2",
        name: "Shampoo Tresemmé 400ml Hidratação Profunda",
        categories: "Perfumaria E Beleza",
        price: 11.9,
        brand: "Tresemmé",
      },
      {
        id: 70712150,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/274586_2",
        name: "Biscoito Wafer Triunfo 115g Choco Avela",
        categories: "Mercearia",
        price: 2.79,
        brand: "Triunfo",
      },
      {
        id: 70709187,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/297205_2",
        name: "Desodorante Aerosol Dove 89g Fem Lavanda Flores Bcas",
        categories: "Perfumaria E Beleza",
        price: 11.9,
        brand: "Dove",
      },
      {
        id: 70710898,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/295373_2",
        name: "Condicionador Dove 400ml Hidratacao Intensa Oxigenio",
        categories: "Perfumaria E Beleza",
        price: 19.99,
        brand: "Dove",
      },
      {
        id: 70710234,
        image: "https://savegnago.vteximg.com.br/arquivos/ids/290662_2",
        name: "Tintura Biocolor Mini Kit 6,6 Vermelho Intenso Vibrante",
        categories: "Perfumaria E Beleza",
        price: 11.19,
        brand: "Biocolor",
      },
    ]),
  down: (QueryInterface) => QueryInterface.bulkDelete("Products", null, {}),
};
